services:
  dozzle:
    image: amir20/dozzle:v10.10.0
    container_name: dozzle
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - dozzle_data:/data
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_NO_ANALYTICS: "true"
      DOZZLE_ADDR: :8080
      DOZZLE_REMOTE_AGENT: 10.1.30.171:7007
      DOZZLE_AUTH_PROVIDER: forward-proxy
      DOZZLE_AUTH_LOGOUT_URL: ${DOZZLE_AUTH_LOGOUT_URL}
    networks:
      macvlan_servers:
        ipv4_address: 10.1.30.43

networks:
  macvlan_servers:
    external: true

volumes:
  dozzle_data: