services:
  immich-public-proxy:
    container_name: immich_public_proxy
    image: alangrainger/immich-public-proxy:3.2.1
    networks:
      macvlan_dmz:
        ipv4_address: 172.16.97.210
        mac_address: 02:AA:97:00:02:10
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      IMMICH_URL: http://10.1.30.46:2283
      PUBLIC_BASE_URL: https://shared-photos.${DOMAIN}
    restart: always

networks:
  macvlan_dmz:
    external: true