services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    mac_address: "02:42:ac:10:0f:24"  # 172.16.15.36
    dns:
      - 10.1.30.101
      - 10.1.30.102
      - 10.1.30.103
    environment:
      - TZ=America/Los_Angeles
      - DISABLE_SSRF_REQUEST_FILTER=1
    volumes:
      - /opt/appdata/audiobookshelf:/config
      - /opt/appdata/audiobookshelf/metadata:/metadata
      - /mnt/nas/audiobooks:/audiobooks
      - /mnt/nas/ebooks:/ebooks
      - /mnt/nas/podcasts:/podcasts
    networks:
      macvlan_media:
        ipv4_address: 172.16.15.36
    restart: unless-stopped
networks:
  macvlan_media:
    external: true