services:
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd:5.1.2-ls270
    container_name: sabnzbd
    mac_address: "02:42:ac:10:0f:1e"  # 172.16.15.30
    dns:
      - 10.1.30.101
      - 10.1.30.102
      - 10.1.30.103
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /opt/appdata/sabnzbd:/config
      - /mnt/nas/downloads:/downloads
    networks:
      macvlan_media:
        ipv4_address: 172.16.15.30
    restart: unless-stopped

networks:
  macvlan_media:
    external: true