services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:8.7.1
    container_name: recyclarr
    mac_address: "02:42:ac:10:0f:1b"
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /opt/appdata/recyclarr:/config
    networks:
      macvlan_media:
        ipv4_address: 172.16.15.27
    restart: unless-stopped

networks:
  macvlan_media:
    external: true