services:
  app:
    image: 'jc21/nginx-proxy-manager:2.15.1'
    restart: unless-stopped
    container_name: nginx-reverse-proxy-internal
    environment:
      TZ: "America/Los_Angeles"
    volumes:
      - /opt/docker/nginx-reverse-proxy-internal/data:/data
      - /opt/docker/nginx-reverse-proxy-internal/letsencrypt:/etc/letsencrypt
    networks:
      macvlan_servers:
        ipv4_address: 10.1.30.175
        mac_address: "b2:9a:52:4d:0b:12"
    dns:
      - 10.1.30.101
      - 10.1.30.103
      - 10.1.30.102
networks:
  macvlan_servers:
    external: true