services:
  app:
    image: 'jc21/nginx-proxy-manager:2.15.1'
    restart: unless-stopped
    hostname: frerp02
    container_name: nginx-reverse-proxy-external
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      TZ: "America/Los_Angeles"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      macvlan_dmz:
        ipv4_address: 172.16.97.200
        mac_address: "42:7e:ec:b0:82:6c"
    dns:
      - 10.1.30.101
      - 10.1.30.103
      - 10.1.30.102
networks:
  macvlan_dmz:
    external: true