services:
  beszel:
    image: henrygd/beszel:0.19.0
    container_name: beszel
    restart: unless-stopped
    environment:
      APP_URL: https://${DOMAIN}
      USER_CREATION: "true"
      DISABLE_PASSWORD_AUTH: "true"
      SHARE_ALL_SYSTEMS: "true"
    volumes:
      - /opt/stacks/beszel/beszel_data:/beszel_data
      - /opt/stacks/beszel/beszel_socket:/beszel_socket
    networks:
      macvlan_servers:
        ipv4_address: 10.1.30.44
        mac_address: 02:42:0a:01:1e:2c

  beszel-agent:
    image: henrygd/beszel-agent:0.19.0
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    depends_on:
      - beszel
    volumes:
      - /opt/stacks/beszel/beszel_agent_data:/var/lib/beszel-agent
      - /opt/stacks/beszel/beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: ${BESZEL_KEY}
      TOKEN: ${BESZEL_TOKEN}

networks:
  macvlan_servers:
    external: true